//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrostyMeshPlugin.Gltf.AutoGenerated {
    using System.Linq;
    using System.Runtime.Serialization;
    using System.Text.Json;
    using System.Text.Json.Serialization;
    
    
    [System.Text.Json.Serialization.JsonConverter(typeof(MaterialOcclusionTextureInfoConverter))]
    public class MaterialOcclusionTextureInfo {
        
        /// <summary>
        /// Backing field for Index.
        /// </summary>
        private int m_index;
        
        /// <summary>
        /// Backing field for TexCoord.
        /// </summary>
        private int m_texCoord = 0;
        
        /// <summary>
        /// Backing field for Strength.
        /// </summary>
        private float m_strength = 1F;
        
        /// <summary>
        /// Backing field for Extensions.
        /// </summary>
        private System.Collections.Generic.Dictionary<string, object> m_extensions;
        
        /// <summary>
        /// Backing field for Extras.
        /// </summary>
        private Extras m_extras;
        
        /// <summary>
        /// The index of the texture.
        /// </summary>
        [System.Text.Json.Serialization.JsonRequiredAttribute()]
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("index")]
        public int Index {
            get {
                return this.m_index;
            }
            set {
                if ((value < 0)) {
                    throw new System.ArgumentOutOfRangeException("Index", value, "Expected value to be greater than or equal to 0");
                }
                this.m_index = value;
            }
        }
        
        /// <summary>
        /// The set index of texture's TEXCOORD attribute used for texture coordinate mapping.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("texCoord")]
        public int TexCoord {
            get {
                return this.m_texCoord;
            }
            set {
                if ((value < 0)) {
                    throw new System.ArgumentOutOfRangeException("TexCoord", value, "Expected value to be greater than or equal to 0");
                }
                this.m_texCoord = value;
            }
        }
        
        /// <summary>
        /// A scalar multiplier controlling the amount of occlusion applied.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("strength")]
        public float Strength {
            get {
                return this.m_strength;
            }
            set {
                if ((value < 0D)) {
                    throw new System.ArgumentOutOfRangeException("Strength", value, "Expected value to be greater than or equal to 0");
                }
                if ((value > 1D)) {
                    throw new System.ArgumentOutOfRangeException("Strength", value, "Expected value to be less than or equal to 1");
                }
                this.m_strength = value;
            }
        }
        
        /// <summary>
        /// JSON object with extension-specific objects.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("extensions")]
        public System.Collections.Generic.Dictionary<string, object> Extensions {
            get {
                return this.m_extensions;
            }
            set {
                this.m_extensions = value;
            }
        }
        
        /// <summary>
        /// Application-specific data.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("extras")]
        public Extras Extras {
            get {
                return this.m_extras;
            }
            set {
                this.m_extras = value;
            }
        }
        
        public bool ShouldSerializeTexCoord() {
            return ((m_texCoord == 0) 
                        == false);
        }
        
        public bool ShouldSerializeStrength() {
            return ((m_strength == 1F) 
                        == false);
        }
        
        public bool ShouldSerializeExtensions() {
            return ((m_extensions == null) 
                        == false);
        }
        
        public bool ShouldSerializeExtras() {
            return ((m_extras == null) 
                        == false);
        }
        
        public class MaterialOcclusionTextureInfoConverter : JsonConverter<MaterialOcclusionTextureInfo> {
            
            public override bool CanConvert(System.Type typeToConvert) {
                return (typeof(MaterialOcclusionTextureInfo) == typeToConvert);
            }
            
            public override MaterialOcclusionTextureInfo Read(ref Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
                if ((reader.TokenType != JsonTokenType.StartObject)) {
                    throw new JsonException();
                }
                MaterialOcclusionTextureInfo foo = new MaterialOcclusionTextureInfo();
                for (
                ; true; 
                ) {
                    if ((reader.Read() == false)) {
break;
                    }
                    if ((reader.TokenType == JsonTokenType.EndObject)) {
break;
                    }
                    if ((reader.TokenType == JsonTokenType.PropertyName)) {
                        string propertyName = reader.GetString();
                        reader.Read();
                        if ((propertyName == "index")) {
                            foo.Index = System.Text.Json.JsonSerializer.Deserialize<int>(ref reader, options);
                        }
                        if ((propertyName == "texCoord")) {
                            foo.TexCoord = System.Text.Json.JsonSerializer.Deserialize<int>(ref reader, options);
                        }
                        if ((propertyName == "strength")) {
                            foo.Strength = System.Text.Json.JsonSerializer.Deserialize<float>(ref reader, options);
                        }
                        if ((propertyName == "extensions")) {
                            foo.Extensions = System.Text.Json.JsonSerializer.Deserialize<System.Collections.Generic.Dictionary<string, object>>(ref reader, options);
                        }
                        if ((propertyName == "extras")) {
                            foo.Extras = System.Text.Json.JsonSerializer.Deserialize<Extras>(ref reader, options);
                        }
                    }
                }
                return foo;
            }
            
            public override void Write(System.Text.Json.Utf8JsonWriter writer, MaterialOcclusionTextureInfo value, System.Text.Json.JsonSerializerOptions options) {
                writer.WriteStartObject();
                writer.WritePropertyName("index");
                System.Text.Json.JsonSerializer.Serialize(writer, value.Index, options);
                if (value.ShouldSerializeTexCoord()) {
                    writer.WritePropertyName("texCoord");
                    System.Text.Json.JsonSerializer.Serialize(writer, value.TexCoord, options);
                }
                if (value.ShouldSerializeStrength()) {
                    writer.WritePropertyName("strength");
                    System.Text.Json.JsonSerializer.Serialize(writer, value.Strength, options);
                }
                if (value.ShouldSerializeExtensions()) {
                    writer.WritePropertyName("extensions");
                    System.Text.Json.JsonSerializer.Serialize(writer, value.Extensions, options);
                }
                if (value.ShouldSerializeExtras()) {
                    writer.WritePropertyName("extras");
                    System.Text.Json.JsonSerializer.Serialize(writer, value.Extras, options);
                }
                writer.WriteEndObject();
            }
        }
    }
}
