//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrostyMeshPlugin.Gltf.AutoGenerated {
    using System.Linq;
    using System.Runtime.Serialization;
    using System.Text.Json;
    using System.Text.Json.Serialization;
    
    
    [System.Text.Json.Serialization.JsonConverter(typeof(SkinConverter))]
    public class Skin {
        
        /// <summary>
        /// Backing field for InverseBindMatrices.
        /// </summary>
        private System.Nullable<int> m_inverseBindMatrices;
        
        /// <summary>
        /// Backing field for Skeleton.
        /// </summary>
        private System.Nullable<int> m_skeleton;
        
        /// <summary>
        /// Backing field for Joints.
        /// </summary>
        private System.Collections.Generic.List<int> m_joints;
        
        /// <summary>
        /// Backing field for Name.
        /// </summary>
        private string m_name;
        
        /// <summary>
        /// Backing field for Extensions.
        /// </summary>
        private System.Collections.Generic.Dictionary<string, object> m_extensions;
        
        /// <summary>
        /// Backing field for Extras.
        /// </summary>
        private Extras m_extras;
        
        /// <summary>
        /// The index of the accessor containing the floating-point 4x4 inverse-bind matrices.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("inverseBindMatrices")]
        public System.Nullable<int> InverseBindMatrices {
            get {
                return this.m_inverseBindMatrices;
            }
            set {
                if ((value < 0)) {
                    throw new System.ArgumentOutOfRangeException("InverseBindMatrices", value, "Expected value to be greater than or equal to 0");
                }
                this.m_inverseBindMatrices = value;
            }
        }
        
        /// <summary>
        /// The index of the node used as a skeleton root.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("skeleton")]
        public System.Nullable<int> Skeleton {
            get {
                return this.m_skeleton;
            }
            set {
                if ((value < 0)) {
                    throw new System.ArgumentOutOfRangeException("Skeleton", value, "Expected value to be greater than or equal to 0");
                }
                this.m_skeleton = value;
            }
        }
        
        /// <summary>
        /// Indices of skeleton nodes, used as joints in this skin.
        /// </summary>
        [System.Text.Json.Serialization.JsonRequiredAttribute()]
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("joints")]
        public System.Collections.Generic.List<int> Joints {
            get {
                return this.m_joints;
            }
            set {
                if ((value == null)) {
                    this.m_joints = value;
                    return;
                }
                if ((value.Count < 1u)) {
                    throw new System.ArgumentException("List not long enough");
                }
                int index = 0;
                for (index = 0; (index < value.Count); index = (index + 1)) {
                    if ((value[index] < 0)) {
                        throw new System.ArgumentOutOfRangeException();
                    }
                }
                this.m_joints = value;
            }
        }
        
        /// <summary>
        /// The user-defined name of this object.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("name")]
        public string Name {
            get {
                return this.m_name;
            }
            set {
                this.m_name = value;
            }
        }
        
        /// <summary>
        /// JSON object with extension-specific objects.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("extensions")]
        public System.Collections.Generic.Dictionary<string, object> Extensions {
            get {
                return this.m_extensions;
            }
            set {
                this.m_extensions = value;
            }
        }
        
        /// <summary>
        /// Application-specific data.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("extras")]
        public Extras Extras {
            get {
                return this.m_extras;
            }
            set {
                this.m_extras = value;
            }
        }
        
        public bool ShouldSerializeInverseBindMatrices() {
            return ((m_inverseBindMatrices == null) 
                        == false);
        }
        
        public bool ShouldSerializeSkeleton() {
            return ((m_skeleton == null) 
                        == false);
        }
        
        public bool ShouldSerializeJoints() {
            return ((m_joints == null) 
                        == false);
        }
        
        public bool ShouldSerializeName() {
            return ((m_name == null) 
                        == false);
        }
        
        public bool ShouldSerializeExtensions() {
            return ((m_extensions == null) 
                        == false);
        }
        
        public bool ShouldSerializeExtras() {
            return ((m_extras == null) 
                        == false);
        }
        
        public class SkinConverter : JsonConverter<Skin> {
            
            public override bool CanConvert(System.Type typeToConvert) {
                return (typeof(Skin) == typeToConvert);
            }
            
            public override Skin Read(ref Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) {
                if ((reader.TokenType != JsonTokenType.StartObject)) {
                    throw new JsonException();
                }
                Skin foo = new Skin();
                for (
                ; true; 
                ) {
                    if ((reader.Read() == false)) {
break;
                    }
                    if ((reader.TokenType == JsonTokenType.EndObject)) {
break;
                    }
                    if ((reader.TokenType == JsonTokenType.PropertyName)) {
                        string propertyName = reader.GetString();
                        reader.Read();
                        if ((propertyName == "inverseBindMatrices")) {
                            foo.InverseBindMatrices = System.Text.Json.JsonSerializer.Deserialize<System.Nullable<int>>(ref reader, options);
                        }
                        if ((propertyName == "skeleton")) {
                            foo.Skeleton = System.Text.Json.JsonSerializer.Deserialize<System.Nullable<int>>(ref reader, options);
                        }
                        if ((propertyName == "joints")) {
                            foo.Joints = System.Text.Json.JsonSerializer.Deserialize<System.Collections.Generic.List<int>>(ref reader, options);
                        }
                        if ((propertyName == "name")) {
                            foo.Name = System.Text.Json.JsonSerializer.Deserialize<string>(ref reader, options);
                        }
                        if ((propertyName == "extensions")) {
                            foo.Extensions = System.Text.Json.JsonSerializer.Deserialize<System.Collections.Generic.Dictionary<string, object>>(ref reader, options);
                        }
                        if ((propertyName == "extras")) {
                            foo.Extras = System.Text.Json.JsonSerializer.Deserialize<Extras>(ref reader, options);
                        }
                    }
                }
                return foo;
            }
            
            public override void Write(System.Text.Json.Utf8JsonWriter writer, Skin value, System.Text.Json.JsonSerializerOptions options) {
                writer.WriteStartObject();
                if (value.ShouldSerializeInverseBindMatrices()) {
                    writer.WritePropertyName("inverseBindMatrices");
                    System.Text.Json.JsonSerializer.Serialize(writer, value.InverseBindMatrices, options);
                }
                if (value.ShouldSerializeSkeleton()) {
                    writer.WritePropertyName("skeleton");
                    System.Text.Json.JsonSerializer.Serialize(writer, value.Skeleton, options);
                }
                writer.WritePropertyName("joints");
                System.Text.Json.JsonSerializer.Serialize(writer, value.Joints, options);
                if (value.ShouldSerializeName()) {
                    writer.WritePropertyName("name");
                    System.Text.Json.JsonSerializer.Serialize(writer, value.Name, options);
                }
                if (value.ShouldSerializeExtensions()) {
                    writer.WritePropertyName("extensions");
                    System.Text.Json.JsonSerializer.Serialize(writer, value.Extensions, options);
                }
                if (value.ShouldSerializeExtras()) {
                    writer.WritePropertyName("extras");
                    System.Text.Json.JsonSerializer.Serialize(writer, value.Extras, options);
                }
                writer.WriteEndObject();
            }
        }
    }
}
